
spring:
  datasource:
    username: postgres
    password: tornado1805
    url: jdbc:postgresql://localhost:5434/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  servlet:
    context-path: /api/v1